services:
  # Main LinkedIn-CRM sync application with web interface
  linkedin-sync:
    build: .
    container_name: linkedin-ai-sync
    network_mode: host
    environment:
      # LinkedIn API Configuration
      - LINKEDIN_ACCESS_TOKEN=${LINKEDIN_ACCESS_TOKEN}

      # Microsoft Dynamics CRM Configuration
      - DYNAMICS_TENANT_ID=${DYNAMICS_TENANT_ID}
      - DYNAMICS_CLIENT_ID=${DYNAMICS_CLIENT_ID}
      - DYNAMICS_CLIENT_SECRET=${DYNAMICS_CLIENT_SECRET}
      - DYNAMICS_CRM_URL=${DYNAMICS_CRM_URL}

      # AI Configuration (connect to host Ollama server via localhost)
      - OLLAMA_MODEL=${OLLAMA_MODEL:-mistral-small:24b}
      - OLLAMA_HOST=${OLLAMA_HOST:-http://localhost:11434}
      - OPENAI_API_KEY=ollama

      # Web Interface Configuration
      - WEB_HOST=0.0.0.0
      - WEB_PORT=19000
      - DATABASE_URL=sqlite:///data/duplicates.db

      # MCP Server Configuration
      - MCP_LINKEDIN_PORT=8001
      - MCP_DYNAMICS_PORT=8002
      - MCP_PLAYWRIGHT_PORT=8003
    volumes:
      # Mount for development (optional - comment out for production)
      - .:/app
      # Persistent storage for logs, database, and results
      - linkedin-sync-data:/app/data
    # Start web interface by default
    stdin_open: true
    tty: true
    command: uv run linkedin-web

volumes:
  # Persistent storage for application data (database, logs, results)
  linkedin-sync-data:
    name: linkedin-sync-app-data